### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by oneohthree** [m0hithreddy/Proxifier-For-Linux#3]
Distribution: Arch Linux
Architecture: x64

I've tried to run Proxifier-For-Linux several times but without luck. I see no issues in logs and have no other info to give on the issue.

In a desperate attempt I tried to run standalone `fakehttpserver` and `fakehttpsserver` both thrown: `Segmentation fault (core dumped)`.

During attempts to run Proxifier I watched my proxy server logs and saw nothing related.

**Comment by MohithReddy2439** [comment]
Trying to see forests through trees you made it worse, If you see the code of fakehttpserver and fakehttpsserver accepts come command line arguments which will be supplied to them at runtime by proxifier file, You tried to run them bare without providing command line arguments which caused segmentation fault.

Regarding proxfier not working on your PC I have no clue I need some info to conclude it ..........

**Comment by oneohthree** [comment]
Can you provide a way to see any logs or debug info?

**Comment by m0hithreddy** [comment]
Hi, 
The codebase is completely revamped. Check the latest ones you wouldn't be having issues. 
Thank You.
