### ISSUE TITLE
Segmentation Fault on Manjaro

### ISSUE THREAD

**Issue by yuniel-acosta** [m0hithreddy/Proxifier-For-Linux#5]
After run proxifier start launch the error

> proxifier start
> **********************************************************************
> 
> PROXIFIER by MOHITH REDDY
> 
> Configuring System......
> 
> /usr/local/bin/proxifier: line 1: 41943 Segmentation fault      sudo /opt/proxifier/bin/proxifier "$@"

Kernel Version 5.5.8-1-MANJARO
OS Type 64-bit

**Comment by m0hithreddy** [comment]
Hi, the codebase is completely revamped. Check the latest ones. Much more professional, efficient, and easily configurable. 
Thank You.
